export {Question} from "./structured-data/interfaces/question";
export {Place} from "./structured-data/interfaces/place";
export {OpeningHoursSpecification} from "./structured-data/interfaces/opening-hours-specification";
export {GeoCoordinates} from "./structured-data/interfaces/geo-coordinates";
export {Business} from "./structured-data/interfaces/business";
export {Answer} from "./structured-data/interfaces/answer";
export {Address} from "./structured-data/interfaces/address";
export {StructuredDataService} from "./structured-data/structured-data.service";
export {StructuredDataModule} from './structured-data/structured-data.module';
